name: agora15min
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  permission_handler: ^9.2.0
  agora_rtc_engine: ^5.1.0
  custom_timer: ^0.1.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/Messanger_back.png
  uses-material-design: true
